// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: webauthn/data/service.proto

package dataconnect

import (
	data "buf.build/gen/go/authaas/webauthn-data/protocolbuffers/go/webauthn/data"
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
)

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "webauthn.data.Service"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceRegisterProcedure is the procedure name of the Service's Register RPC.
	ServiceRegisterProcedure = "/webauthn.data.Service/Register"
	// ServiceLoginProcedure is the procedure name of the Service's Login RPC.
	ServiceLoginProcedure = "/webauthn.data.Service/Login"
	// ServiceGetCredentialProcedure is the procedure name of the Service's GetCredential RPC.
	ServiceGetCredentialProcedure = "/webauthn.data.Service/GetCredential"
	// ServiceSetLoginChallengeProcedure is the procedure name of the Service's SetLoginChallenge RPC.
	ServiceSetLoginChallengeProcedure = "/webauthn.data.Service/SetLoginChallenge"
)

var (
	serviceRegisterSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_webauthn_data_service_proto.Services().ByName("Service").Methods().ByName("Register"),
			Procedure:  ServiceRegisterProcedure,
		}
	})
	serviceLoginSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_webauthn_data_service_proto.Services().ByName("Service").Methods().ByName("Login"),
			Procedure:  ServiceLoginProcedure,
		}
	})
	serviceGetCredentialSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_webauthn_data_service_proto.Services().ByName("Service").Methods().ByName("GetCredential"),
			Procedure:  ServiceGetCredentialProcedure,
		}
	})
	serviceSetLoginChallengeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_webauthn_data_service_proto.Services().ByName("Service").Methods().ByName("SetLoginChallenge"),
			Procedure:  ServiceSetLoginChallengeProcedure,
		}
	})
)

// ServiceClient is a client for the webauthn.data.Service service.
type ServiceClient interface {
	// Establishes an identity with its credential. Refuses when either is
	// already established, and establishes nothing.
	Register(context.Context, *data.RegisterRequest) (*data.RegisterResponse, error)
	// Consumes the exact challenge and records the authentication: the
	// credential's login state, and the identity's new grant and when it
	// authenticated. Refuses when the challenge is not current, and records
	// nothing.
	Login(context.Context, *data.LoginRequest) (*data.LoginResponse, error)
	// The credential's record. Refuses an unknown credential.
	GetCredential(context.Context, *data.GetCredentialRequest) (*data.GetCredentialResponse, error)
	// Replaces the credential's login challenge; answers once it is durable.
	// Refuses an unknown credential.
	SetLoginChallenge(context.Context, *data.SetLoginChallengeRequest) (*data.SetLoginChallengeResponse, error)
}

// NewServiceClient constructs a client for the webauthn.data.Service service. Multiple service
// clients may share a single connect.Client.
func NewServiceClient(client *connect.Client) ServiceClient {
	return &serviceClient{client: client}
}

// ServiceHandler is an implementation of the webauthn.data.Service service.
type ServiceHandler interface {
	// Establishes an identity with its credential. Refuses when either is
	// already established, and establishes nothing.
	Register(context.Context, *data.RegisterRequest) (*data.RegisterResponse, error)
	// Consumes the exact challenge and records the authentication: the
	// credential's login state, and the identity's new grant and when it
	// authenticated. Refuses when the challenge is not current, and records
	// nothing.
	Login(context.Context, *data.LoginRequest) (*data.LoginResponse, error)
	// The credential's record. Refuses an unknown credential.
	GetCredential(context.Context, *data.GetCredentialRequest) (*data.GetCredentialResponse, error)
	// Replaces the credential's login challenge; answers once it is durable.
	// Refuses an unknown credential.
	SetLoginChallenge(context.Context, *data.SetLoginChallengeRequest) (*data.SetLoginChallengeResponse, error)
}

// RegisterServiceHandler registers svc as the webauthn.data.Service implementation on server.
func RegisterServiceHandler(server *connect.Server, svc ServiceHandler) {
	adapter := serviceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: serviceRegisterSpec(), Handler: adapter.register},
		connect.Method{Spec: serviceLoginSpec(), Handler: adapter.login},
		connect.Method{Spec: serviceGetCredentialSpec(), Handler: adapter.getCredential},
		connect.Method{Spec: serviceSetLoginChallengeSpec(), Handler: adapter.setLoginChallenge},
	)
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Register(context.Context, *data.RegisterRequest) (*data.RegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "webauthn.data.Service.Register is not implemented")
}

func (UnimplementedServiceHandler) Login(context.Context, *data.LoginRequest) (*data.LoginResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "webauthn.data.Service.Login is not implemented")
}

func (UnimplementedServiceHandler) GetCredential(context.Context, *data.GetCredentialRequest) (*data.GetCredentialResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "webauthn.data.Service.GetCredential is not implemented")
}

func (UnimplementedServiceHandler) SetLoginChallenge(context.Context, *data.SetLoginChallengeRequest) (*data.SetLoginChallengeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "webauthn.data.Service.SetLoginChallenge is not implemented")
}

type serviceClient struct {
	client *connect.Client
}

func (c *serviceClient) Register(ctx context.Context, req *data.RegisterRequest) (*data.RegisterResponse, error) {
	var res data.RegisterResponse
	if err := c.client.CallUnary(ctx, serviceRegisterSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *serviceClient) Login(ctx context.Context, req *data.LoginRequest) (*data.LoginResponse, error) {
	var res data.LoginResponse
	if err := c.client.CallUnary(ctx, serviceLoginSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *serviceClient) GetCredential(ctx context.Context, req *data.GetCredentialRequest) (*data.GetCredentialResponse, error) {
	var res data.GetCredentialResponse
	if err := c.client.CallUnary(ctx, serviceGetCredentialSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *serviceClient) SetLoginChallenge(ctx context.Context, req *data.SetLoginChallengeRequest) (*data.SetLoginChallengeResponse, error) {
	var res data.SetLoginChallengeResponse
	if err := c.client.CallUnary(ctx, serviceSetLoginChallengeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type serviceHandler struct{ svc ServiceHandler }

func (h serviceHandler) register(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.RegisterRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Register(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h serviceHandler) login(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.LoginRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Login(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h serviceHandler) getCredential(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.GetCredentialRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetCredential(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h serviceHandler) setLoginChallenge(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.SetLoginChallengeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.SetLoginChallenge(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
